### ISSUE TITLE
Cannot launch the sample app

### ISSUE THREAD

**Issue by grishick** [circlefin/payments-sample-app#152]
I pulled the code, followed the instructions from the documentation and I get this error when running 'yarn dev'

yarn run v1.22.17
$ cross-env NODE_ENV=development nuxt

   ╭────────────────────────────────────────╮
   │                                        │
   │   Nuxt @ v2.15.8                       │
   │                                        │
   │   ▸ Environment: development           │
   │   ▸ Rendering:   client-side           │
   │   ▸ Target:      server                │
   │                                        │
   │   Listening: http://10.0.0.119:3011/   │
   │                                        │
   ╰────────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                    13:04:55
ℹ Initial build may take a while                                                                                                                                       13:04:55
✔ Builder initialized                                                                                                                                                  13:04:55
✔ Nuxt files generated                                                                                                                                                 13:04:55

● Client █████████████████████████ building (10%) 1/4 modules 3 active
 babel-loader › .nuxt/client.js

 ERROR  Error: error:0308010C:digital envelope routines::unsupported                                                                                                   13:04:56
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/gsolovyev/git/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/gsolovyev/git/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/gsolovyev/git/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/gsolovyev/git/payments-sample-app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by grishick** [comment]
Found my problem, webpack does not work with Node 17. Installing the latest LTS version resolved the issue.
