### ISSUE TITLE
Cloning on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by cryptoHF** [circlefin/payments-sample-app#268]
#Hello, I'm trying to set up the cloning on my local terminal and I get these errors after running command: ( yarn install ). 

ℹ Preparing project for development                                                14:23:37
ℹ Initial build may take a while                                                          14:23:37
✔ Builder initialized                                                                            14:23:37
✔ Nuxt files generated                                                                       14:23:37

● Client █████████████████████████ building (10%) 1/2 modules 1 active
 node_modules/webpack-hot-middleware/client.js

 ERROR  Error: error:0308010C:digital envelope routines::unsupported  14:23:39 at new Hash (node:internal/crypto/hash:71:19
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/Meister/payments-sample-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/Meister/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16) at /Users/Meister/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

node:internal/crypto/hash:71 this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/Meister/payments-sample-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/Meister/payments-sample-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/Meister/payments-sample-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/Meister/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16) at /Users/Meister/payments-sample-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9 at /Users/Meister/payments-sample-app/node_modules/graceful-fs/graceful-fs.js:123:16 at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
///user path hidden/// payments-sample-app % node:internal/process/promises:288 triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 13669.
    at /Users/Meister/payments-sample-app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47 at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v18.12.0
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 13668.
    at /Users/Meister/payments-sample-app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47 at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

#I've tried to update the plugins w/ dependency errors, however, when I run command: (  yarn dev ) http://localhost:3011/ link shows an ERROR. Is this normal? 

#note* I haven't used git cloning in a while. Thanks in advance.

**Comment by cryptoHF** [comment]
when I execute:  (  yarn run test ) I get the following. 
$ jest
 PASS  test/unit/lib/apiTarget.spec.js
  apiTarget
    ✓ returns environment variable if localhost (4 ms)
    ✓ correctly translates known hostnames (2 ms)

------------------------------|---------|----------|---------|---------|-------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------|---------|----------|---------|---------|-------------------
All files                     |    1.15 |     3.03 |    0.89 |    0.77 |                   
 lib                          |    1.65 |     4.11 |    1.32 |     1.1 |                   
  achApi.ts                   |       0 |        0 |       0 |       0 | 1-100             
  achTestData.ts              |       0 |      100 |     100 |       0 | 1-22              
  addressesApi.ts             |       0 |        0 |       0 |       0 | 1-92              
  apiTarget.ts                |   69.23 |      100 |      50 |      60 | 23-29             
  applePay.ts                 |       0 |        0 |       0 |       0 | 1-287             
  cardTestData.ts             |       0 |      100 |     100 |       0 | 1                 
  cardsApi.ts                 |       0 |        0 |       0 |       0 | 1-136             
  chargebacksApi.ts           |       0 |        0 |       0 |       0 | 1-90              
  cryptoPaymentMetadataApi.ts |       0 |        0 |       0 |       0 | 1-44              
  eventBus.js                 |       0 |      100 |     100 |       0 | 2                 
  googlePay.ts                |       0 |        0 |       0 |       0 | 1-180             
  marketplaceApi.ts           |       0 |        0 |       0 |       0 | 1-210             
  mocksApi.ts                 |       0 |        0 |       0 |       0 | 1-108             
  navigatorInfo.ts            |       0 |        0 |       0 |       0 | 2-10              
  openpgp.ts                  |       0 |        0 |       0 |       0 | 1-34              
  paymentIntentsApi.ts        |       0 |        0 |       0 |       0 | 1-118             
  paymentsApi.ts              |       0 |        0 |       0 |       0 | 1-226             
  payoutsApi.ts               |       0 |        0 |       0 |       0 | 1-143             
  sepaApi.ts                  |       0 |        0 |       0 |       0 | 1-79              
  sepaTestData.ts             |       0 |      100 |     100 |       0 | 1                 
  settlementsApi.ts           |       0 |        0 |       0 |       0 | 1-96              
  transfersApi.ts             |       0 |        0 |       0 |       0 | 1-123             
  walletsApi.ts               |       0 |        0 |       0 |       0 | 1-125             
  wiresApi.ts                 |       0 |        0 |       0 |       0 | 1-106             
  wiresTestData.ts            |       0 |      100 |     100 |       0 | 1                 
 lib/beta                     |       0 |        0 |       0 |       0 |                   
  paymentsApi.ts              |       0 |        0 |       0 |       0 | 1-76              
  payoutsApi.ts               |       0 |        0 |       0 |       0 | 1-129             
 lib/businessAccount          |       0 |        0 |       0 |       0 |                   
  addressesApi.ts             |       0 |        0 |       0 |       0 | 1-113             
  balancesApi.ts              |       0 |        0 |       0 |       0 | 1-45              
  bankAccountsApi.ts          |       0 |        0 |       0 |       0 | 1-115             
  bankAccountsTestData.ts     |       0 |      100 |     100 |       0 | 1                 
  depositsApi.ts              |       0 |        0 |       0 |       0 | 1-72              
  payoutsApi.ts               |       0 |        0 |       0 |       0 | 1-103             
  senAccountsApi.ts           |       0 |        0 |       0 |       0 | 1-77              
  transfersApi.ts             |       0 |        0 |       0 |       0 | 1-106             
 store                        |       0 |        0 |       0 |       0 |                   
  index.ts                    |       0 |        0 |       0 |       0 | 1-90              
------------------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        23.066 s, estimated 35 s
Ran all test suites.
✨  Done in 32.78s.

**Comment by cryptoHF** [comment]
### I was able to correct this issue with the following: 

_run command_        


  

- > ### export NODE_OPTIONS=--openssl-legacy-provider



_run command_ 



- > ### yarn dev

Payment-sample-app loads in local as desired
